### ISSUE TITLE
Reduce Lambda Final Bundle size.

### ISSUE THREAD

**Issue by CharanRoot** [Dynatrace/serverless-oneagent#12]
Dynatrace is Increasing Lambda Bundle size drastically. I observed that on Average bundle zip size increased by 19+ MB in Node 10.x.

Before Dynatrace our lambda bundle size is 2MB
After adding Dynatrace its increased by 21 MB.

My environment is Nodejs 10.x and final package build was tailor to `--AwsLambdaV10`

I observed that Dynatrace final bundle zip have non minified code, lot of unnecessary package and unnecessary files.
example :- By default AWS lambda provide  aws-sdk in Runtime environment  but Dynatrace include in the node_modules.

Is their way or config to reduce and remove unnecessary package from node_modules. 

![image](https://user-images.githubusercontent.com/27700962/66684534-cf81dd00-ec3f-11e9-84fd-ca16c0ba934d.png)

**Comment by Hollerberg** [comment]
Not sure where the aws-sdk dependency origins from - it is not a dependency introduced by Dynatrace OneAgent. I packaged the aws-lambda-node.js from the serverless-oneagent samples folder and the resulting zip file did not include aws-sdk.

Please make sure, that you did add @dynatrace/serverless-oneagent plugin as development dependency (`npm i --save-dev @dynatrace/serverless-oneagent`). Nonetheless. you will notice that the packaged zip file size will increase by several MB. The main contributors are native extensions (*.node) and shared object files of Dynatrace OneAgent.

**Comment by CharanRoot** [comment]
@Hollerberg 
are you able deploy and invoke your Node sample application `aws-lambda-node.js`.

Our Lambda is throwing Module error after moving dynatrace dependency  into dev.
```
{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'index'","trace":["Runtime.ImportModuleError: Error: Cannot find module 'index'","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:45:30)","    at Module._compile (internal/modules/cjs/loader.js:778:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)","    at Module.load (internal/modules/cjs/loader.js:653:32)","    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)","    at Function.Module._load (internal/modules/cjs/loader.js:585:3)","    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)","    at startup (internal/bootstrap/node.js:283:19)"]}
```

`package.json `
```
{
    "name": "dummyservice",
    "dependencies": {
        "@hapi/joi": "15.0.3",
        "inversify": "4.13.0",
        "reflect-metadata": "0.1.13",
        "uuid": "3.3.3"
    },
    "devDependencies": {
        "serverless": "1.51.0",
        "typescript": "3.5.2",
        "@dynatrace/serverless-oneagent": "^1.0.10",
        "@dynatrace/oneagent": "^1.175.270-1.0.0"
    },
}
```

**Comment by Hollerberg** [comment]
Yes, deployment and running the function works. 

Please only make `@dynatrace/serverless-oneagent` a development dependency. It is not needed in the final bundle. 

Did you by intent add `"@dynatrace/oneagent": "^1.175.270-1.0.0"` to package.json? The serverless plugin will install @dynatrace/oneagent automatically and typically there is no need to have it in your package.json.

For reference, you can lookup the sample here https://gist.github.com/Hollerberg/7cb0d5719a6c43334ff0b3729f0ab99f

**Comment by charanack** [comment]
@Hollerberg
I am using `Yarn` so auto install not working

```
 Error: Command failed: yarn install --frozen-lockfile --non-interactive
  error Couldn't find any versions for "@dynatrace/oneagent" that matches "*"
```
i tried to add `yarn add "@dyntrace/oneagent@1.175.270-1.0.0"`  and yarn throwing error 
```
yarn add v1.9.4
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@dyntrace%2foneagent: Not found".
```
how to configure oneagent using `yarn` ?

**Comment by CharanRoot** [comment]
@Hollerberg
I am using `Yarn` so auto install not working

```
 Error: Command failed: yarn install --frozen-lockfile --non-interactive
  error Couldn't find any versions for "@dynatrace/oneagent" that matches "*"
```
i tried to add `yarn add "@dyntrace/oneagent@1.175.270-1.0.0"`  and yarn throwing error 
```
yarn add v1.9.4
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@dyntrace%2foneagent: Not found".
```
how to configure oneagent using `yarn` ?

**Comment by Hollerberg** [comment]
I do not use yarn, but you misspelled dynatrace in `yarn add "@dyntrace/oneagent@1.175.270-1.0.0"` (an a is missing). Using the correct spelling, installs the package without errors.

Please refer to https://github.com/Dynatrace/serverless-oneagent/issues/4#issuecomment-446278007 on how to use yarn with the serverless plugin.

Getting back to the original issue. Please make sure that @dynatrace/serverless-oneagent is a development dependency (which should not be bundled to your function) and @dynatrace/oneagent is a normal (non-development) dependency, as it has to be bundled with your function.

**Comment by CharanRoot** [comment]
sorry I copied yarn add command from your github issue #4 ([comment](https://github.com/Dynatrace/serverless-oneagent/issues/4#issuecomment-446278007)) can you update in your github comment 4.

what is the difference between yarn add vs adding dependency  in the package.json file. I think it will results same.

updated package.json 
```
 "dependencies": {
        "reflect-metadata": "0.1.13",
        "@dynatrace/oneagent": "1.177.216-1.0.0"
        },
    "devDependencies": {
        "serverless": "1.51.0",
        "typescript": "3.5.2",
        "@dynatrace/serverless-oneagent": "^1.0.10"
    },
```
I created basic NPM based serverless-webpack [project](https://github.com/CharanRoot/Dynatrace_AWS_Serverless) and final build size is 12.3 MB.

Final bundle have unnecessary test, README, and example folders. I think Dynatrace can optimize bundle size by remove these test, debug, readme folder  and minify the required files.

Is their way i can decrease bundle size ?

![image](https://user-images.githubusercontent.com/27700962/66939537-d8d8c400-f008-11e9-816b-f2bf2bd7cd36.png)

![image](https://user-images.githubusercontent.com/27700962/66939798-5e5c7400-f009-11e9-85a6-ceaded9e7f1b.png)

**Comment by Hollerberg** [comment]
Thanks for pointing this out. I will add your proposal to minimize the dependent packages to proposed improvements list. 
Short term, you might configure serverless framework to exclude files to further reduce the bundle size. 

e.g.

```
package:
  exclude:
    - '**/*.md'
    - '**/test/**'
```
