### ISSUE TITLE
Build size increase for exclude functions

### ISSUE THREAD

**Issue by CharanRoot** [Dynatrace/serverless-oneagent#15]
Hi,

I Don't need Dynatrace  for few lambda in my service  so I used `exclude` option.
In verbose I see that Dyntrace excluded function      
`Serverless: [Dynatrace OneAgent] function hello2 has been excluded from monitoring`

Final build of the excluded functions contains all the dynatrace dependency. can we remove these dependency ?

Sample Project
https://github.com/CharanRoot/Dynatrace_AWS_Serverless
In the above repo I exclude `hello2` lambda but final build have all the dynatrace dependency 
![image](https://user-images.githubusercontent.com/27700962/69893467-65002b80-12d7-11ea-8a76-dae97784770a.png)

**Comment by Hollerberg** [comment]
Thank you for the report.

Unluckily, this cannot be fixed on serverless-oneagent plugin level. The plugin uses WebPack configuration (`webpack.includeModules.forceInclude`) to enforce addition oneagent npm module to the deployment. This WebPack configuration option is on service (top level) and not on function level. 

```yaml
custom:
  webpack:
    includeModules:
      forceInclude:
```

This [comment](https://github.com/Dynatrace/serverless-oneagent/issues/14#issuecomment-554347514) already included the heads up for that limitation.
