### ISSUE TITLE
Automatic `npm uninstall` may fail depending on project tooling

### ISSUE THREAD

**Issue by tcarrio** [Dynatrace/serverless-oneagent#17]
This plugin performs an uninstall of itself using `npm` by default. This can cause issues with certain tools that manage monorepositories such as [lerna](https://github.com/lerna/lerna). In the case of Lerna, this tooling is not compatible with `npm` for managing packages due to how it manages internal dependencies of packages, and is a [common issue](https://github.com/lerna/lerna/issues/1229#issuecomment-359508643).

Due to this, the `serverless-oneagent` plugin will fail during the `npm uninstall` stage.

I would suggest an option in the plugin configuration within `serverless.yml` and a CLI argument be provided to disable the uninstall stage. This would allow any tooling that may not work with `npm` to disable the uninstall stage to bypass the issues, while not being vendor-specific.

**Comment by Hollerberg** [comment]
resolved within PR https://github.com/Dynatrace/serverless-oneagent/pull/18 (many thanks to @tcarrio)
