### ISSUE TITLE
What should I expect ?

### ISSUE THREAD

**Issue by quentinhayot** [Dynatrace/serverless-oneagent#19]
Hi,

I just installed this serverless plugin on one of my stacks with no webpack involved.
Now I made some requests to my service, but I'm not sure what I should expect to see on Dynatrace's dashboard. For now, there is nothing new from what I can see.

**Where can I trace those requests on Dynatrace's dashboard? How do I know if it's working at all?**

My config looks like this (please tell me if it's wrong) :

- server: I tried "" (empty) and "*mytenantid*.live.dynatrace.com"
- tenant: *mytenantid*
- tenanttoken: a PaaS token generated on the dashboard

I have no other option set.

Thanks !

**Comment by Hollerberg** [comment]
Dear @quentinhayot ,
thank you for your message. Please get in contact with your Dynatrace representative. Read [here](https://www.dynatrace.com/support/help/technology-support/cloud-platforms/amazon-web-services/installation/integrate-nodejs-lambda-functions) for further information.
