### ISSUE TITLE
semver dependency missing?

### ISSUE THREAD

**Issue by MichaelBosch** [Dynatrace/serverless-oneagent#21]
We see this error on Lambda about missing semver.  When added as a dependency, it works.

Lambda execution failed with status 200 due to customer function error: Error: Cannot find module 'semver'
Require stack:
- /var/task/node_modules/@dynatrace/oneagent-dependency/agent/bin/1.185.131.20200210-080232/any/nodejs/nodejsagent.js

**Comment by Hollerberg** [comment]
hi @MichaelBosch, 
the semver dependency is correctly in place, but it seems that serverless framework packaging process has changed. I am still analyzing, but can confirm the issue. In my test setup, debug package was missing from the bundle, too. 

I identified a more generic workaround: 

Add `@dynatrace/oneagent` to your package.json dependencies (e.g. `npm install --save @dynatrace/oneagent`) and (if specified) remove the oneagent-serverless `npmModuleVersion` option from serverless.yml.

This worked in my test setup (also specifying `excludeDevDependencies: false` in serverless.yml, but this might induce not acceptable side effects).

**Comment by Hollerberg** [comment]
Closing as plugin is deprecated
