### ISSUE TITLE
serverless-onagent && OpenTelemetry

### ISSUE THREAD

**Issue by jdhom** [Dynatrace/serverless-oneagent#22]
Where will serverless framework OpenTelemetry support be added here?
Has work started on the serverless framework plugin for dynatrace opentelemetry?

Best,
/jhd

**Comment by Hollerberg** [comment]
Dear John,
thank you for your inquiry! As your questions relate to potential upcoming product features, could you please refer your questions to your Dynatrace representative. 
Best
Gernot
