### ISSUE TITLE
dt-oneagent-tailor step fails on oneagent 1.185+

### ISSUE THREAD

**Issue by alexanderluchs** [Dynatrace/serverless-oneagent#23]
**Context:**
When running sls deploy or sls package, the serverless-oneagent plugin runs the dt-oneagent-tailor on the `@dynatrace/oneagent` dependency in order to pull out unnecessary code for the target node runtime.  It should be noted that webpack is also being used.

These steps are running inside a build docker container based on `lambci/lambda:build-nodejs10.x`

**Expected results:** 
For all versions of `@dynatrace/oneagent`, the tailoring completes successfully and the unnecessary versions are removed from the final zip package that is uploaded to AWS Lambda.

**Actual results:**
On versions 1.185 and 1.187 of `@dynatrace/oneagent`, the following output is returned from the sls package/deploy command.  Subsequently, the package is not size-optimized for lambda deployment.
```
Serverless: [Dynatrace OneAgent] tailoring OneAgent module in /<path-to-service-src>/.webpack/health
Serverless: [Dynatrace OneAgent] executing /<path-to-service-src>/.webpack/health/node_modules/.bin/dt-oneagent-tailor --AwsLambdaV10
Serverless: [Dynatrace OneAgent] /usr/bin/env: node\r: No such file or directory
Serverless: [Dynatrace OneAgent] could not determine serverless-webpack intermediate files to tailor OneAgentnpm module(things will work, but zip package will contain files not need for selected Node.js runtime version
```

Note that this was also tested outside the docker container on Windows 10 where it was successful and on Mac OS X 10.14.6 where the same error occurred as above.

**Impact:**
Our organization must pin to 1.181 which is the latest available version that does not manifest the issue.  We would like to continue to use latest and greatest but size impact of 1.185+ is not worth the cost of the size increase at this time.

**Possible root cause:**
Based on the `\r` output in the error message and it working on Windows, it appears this might be related to some kind of line ending parsing issue that is not cross-platform.

**Comment by Hollerberg** [comment]
Hi Alexander,
thanks for reporting this issue. 

I suspect that @dynatrace/oneagent package might be the culprit. It seems that the package contains files with \r\n line endings since 1.183. This makes the shebang in `lib/pkgtailor.js` fail (this is my current assumption). 

I packaged a test project with 1.185 in lambci/lambda:build-nodejs10.x container to ascertain my assumption, but failed to reproduce the error. I will investigate further and keep you posted.

**Comment by alexanderluchs** [comment]
Thanks for responding quickly!  If it's helpful, it might be worth mentioning that running the npx dt-oneagent-tailor command manually works, it's only in the context of an sls package or sls deploy where we get the error output mentioned in the issue.

**Comment by Hollerberg** [comment]
Hi Alexander,
any chance you are using `yarn` (or some other package manager then `npm`)? `npm` converts the shebang line endings automatically to \n, while this is not done by e.g. `yarn`. That could be the reason I could not reproduce the issue.

We will re-publish the affected @dynatrace/oneagent packages. That should resolve the issue.

**Comment by Flarna** [comment]
I just published `@dynatrace/oneagent@1.187.155-1.0.1` and `@dynatrace/oneagent@1.185.137-1.0.1` which should fix this problem.

**Comment by Hollerberg** [comment]
Dear Alexander,
`dynatrace/oneagent@1.185.137-1.0.1` and `@dynatrace/oneagent@1.187.155-1.0.1` have been published. Please let us know if that solved the issue.

**Comment by alexanderluchs** [comment]
Incredible response! We'll test this out today and close the issue if that resolves it.

**Comment by alexanderluchs** [comment]
Oh! Also, I forgot to answer your question - yes, we're using yarn.  That's good to have the discrepancy in repro explained.

**Comment by alexanderluchs** [comment]
We are no longer getting the error messages in the tailoring step and our deployed lambda functions are back to being nice and small on the newer versions of the OneAgent library.  Thank you again for such a quick response!
