### ISSUE TITLE
Serverless dynatrace - Known issues Handler functions in sub-folders 

### ISSUE THREAD

**Issue by rolands7** [Dynatrace/serverless-oneagent#24]
Hi i am integrating serverless aws using nodejs 10.0 with dynatrace managed. I have followed the documentation and encountered a known error "Handler functions in sub-folders"

![image](https://user-images.githubusercontent.com/62583152/77386801-bdad7580-6d59-11ea-81aa-25ba26e63bb1.png)

We found in the documentation that it is a known error "Handler functions in sub-folders" and we applied the indicated recommendation,

link: 

https://www.dynatrace.com/support/help/technology-support/cloud-platforms/amazon-web-services/installation/integrate-nodejs-lambda-functions/

apply the settings indicated in the documentation

DT_LAMBDA_HANDLER = lib/index.handler
function definition =_modules/@dynatrace/oneagent/index.handler

shows the following error:

START RequestId: 22d89c65-2c58-4eb0-ad33-9883648e3f89 Version: $LATEST
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: 0x55fb1f38b1d3 node::Abort() [/var/lang/bin/node]
 2: 0x55fb1f38b22f  [/var/lang/bin/node]
 3: 0x55fb1f5cd309 v8::Utils::ReportApiFailure(char const*, char const*) [/var/lang/bin/node]
 4: 0x7f73f914283d  [/var/task/node_modules/@dynatrace/oneagent-dependency/agent/bin/1.187.155.20200304-124853/linux-x86-64/oneagentnode_64.node]
 5: 0x7f73f91416b5  [/var/task/node_modules/@dynatrace/oneagent-dependency/agent/bin/1.187.155.20200304-124853/linux-x86-64/oneagentnode_64.node]
 6: 0x55fb1fb82338 v8::internal::PropertyCallbackArguments::CallNamedGetter(v8::internal::Handle<v8::internal::InterceptorInfo>, v8::internal::Handle<v8::internal::Name>) [/var/lang/bin/node]
 7: 0x55fb1fb8413b  [/var/lang/bin/node]
 8: 0x55fb1fbb4d47 v8::internal::Object::GetProperty(v8::internal::LookupIterator*) [/var/lang/bin/node]
 9: 0x55fb1fadfe64 v8::internal::LoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>) [/var/lang/bin/node]
10: 0x55fb1fae02fc v8::internal::KeyedLoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/var/lang/bin/node]
11: 0x55fb1fae098b v8::internal::Runtime_KeyedLoadIC_Miss(int, v8::internal::Object*, v8::internal::Isolate) [/var/lang/bin/node]
12: 0x2b0973a5be1d 
END RequestId: 22d89c65-2c58-4eb0-ad33-9883648e3f89
REPORT RequestId: 22d89c65-2c58-4eb0-ad33-9883648e3f89	Duration: 3414.64 ms	Billed Duration: 3500 ms	Memory Size: 512 MB	Max Memory Used: 69 MB	
RequestId: 22d89c65-2c58-4eb0-ad33-9883648e3f89 Error: Runtime exited with error: signal: aborted (core dumped)
Runtime.ExitError

it is possible that it is the agent version, I am using the latest version (1.187.155-1.0.1) maybe this version has some incompatibility, I am thinking of using an older version (1.185.137-1.0.1).

Thanks

**Comment by Hollerberg** [comment]
Dear @rolands7,
This crash is a follow up error which only happens, if there loading the handler function (in your case lib/index.handler) failed. Some error conditions that might make the handler function loading fail:
- lib/index.js does not exist
- lib/index.js does not export "handler"
- lib/index.js has a syntax error (e.g. a missing dependency that make a `require` fail)

Unluckily, the follow up crash in the agent hides this underlying error condition. Could you (best in AWS console) revert the handler definition from `node_modules/@dynatrace/oneagent/index.handler` to `lib/index.handler` and then make a test invocation? This will bypass Dynatrace OneAgent and you should see the error which makes your function loading fail.

btw. the crash in the agent has been fixed in newer versions of the agent.

**Comment by rolands7** [comment]
Hello Hollerberg, thanks for your answer, I will detail the problem I have more clearly

I have a function that has a handler definition:

**LMBJVVMTOCOTIZACION/src/controllers/ProductController.selectProduct**

to monitor with dynatrace the documentation asks to install the dynatrace modules:
**npm install -S @dynatrace/oneagent@next
npx dt-oneagent-tailor --AwsLambdaV10**

and add an environment variable  and 
change the name of the controller for it:

**node_modules/@dynatrace/oneagent.LMBJVVMTOCOTIZACION/src/controllers/ProductController$selectProduct**

when making this change and testing I have the following error

![image](https://user-images.githubusercontent.com/62583152/77443742-460f3300-6db9-11ea-9027-8ee566692166.png)

We found in the dynatrace  documentation that it is a known error **"Handler functions in sub-folders"**

link:  https://www.dynatrace.com/support/help/technology-support/cloud-platforms/amazon-web-services/installation/integrate-nodejs-lambda-functions/

honestly for me the documentation is not clear, and what I did was add

**DT_LAMBDA_HANDLER** = lib/index.handler
**handler function** = node_modules/@dynatrace/oneagent/index.handle

**_I'm not sure if this change I've made is correct according to the documentation._**
**Can you confirm if these values of the environment variable and handler function are correct?**

shows the following error:

START RequestId: 22d89c65-2c58-4eb0-ad33-9883648e3f89 Version: $LATEST
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
1: 0x55fb1f38b1d3 node::Abort() [/var/lang/bin/node]
2: 0x55fb1f38b22f [/var/lang/bin/node]
3: 0x55fb1f5cd309 v8::Utils::ReportApiFailure(char const*, char const*) [/var/lang/bin/node]
4: 0x7f73f914283d [/var/task/node_modules/@dynatrace/oneagent-dependency/agent/bin/1.187.155.20200304-124853/linux-x86-64/oneagentnode_64.node]
5: 0x7f73f91416b5 [/var/task/node_modules/@dynatrace/oneagent-dependency/agent/bin/1.187.155.20200304-124853/linux-x86-64/oneagentnode_64.node]
6: 0x55fb1fb82338 v8::internal::PropertyCallbackArguments::CallNamedGetter(v8::internal::Handlev8::internal::InterceptorInfo, v8::internal::Handlev8::internal::Name) [/var/lang/bin/node]
7: 0x55fb1fb8413b [/var/lang/bin/node]
8: 0x55fb1fbb4d47 v8::internal::Object::GetProperty(v8::internal::LookupIterator*) [/var/lang/bin/node]
9: 0x55fb1fadfe64 v8::internal::LoadIC::Load(v8::internal::Handlev8::internal::Object, v8::internal::Handlev8::internal::Name) [/var/lang/bin/node]
10: 0x55fb1fae02fc v8::internal::KeyedLoadIC::Load(v8::internal::Handlev8::internal::Object, v8::internal::Handlev8::internal::Object) [/var/lang/bin/node]
11: 0x55fb1fae098b v8::internal::Runtime_KeyedLoadIC_Miss(int, v8::internal::Object*, v8::internal::Isolate) [/var/lang/bin/node]
12: 0x2b0973a5be1d
END RequestId: 22d89c65-2c58-4eb0-ad33-9883648e3f89
REPORT RequestId: 22d89c65-2c58-4eb0-ad33-9883648e3f89 Duration: 3414.64 ms Billed Duration: 3500 ms Memory Size: 512 MB Max Memory Used: 69 MB
RequestId: 22d89c65-2c58-4eb0-ad33-9883648e3f89 Error: Runtime exited with error: signal: aborted (core dumped)
Runtime.ExitError

---------------------------------------
responding to your instructions,

_**Unluckily, the follow up crash in the agent hides this underlying error condition. Could you (best in AWS console) revert the handler definition from node_modules/@dynatrace/oneagent/index.handler to lib/index.handler and then make a test invocation? This will bypass Dynatrace OneAgent and you should see the error which makes your function loading fail.**_

I have made the changes you indicate, and i have the following errors.

START RequestId: 29afd153-8a0c-4c60-b08f-db2883d4665d Version: $LATEST
2020-03-24T15:08:30.918Z	undefined	ERROR	Uncaught Exception	{"errorType":"Runtime.HandlerNotFound","errorMessage":"lib/index.handler is undefined or not exported","stack":["Runtime.HandlerNotFound: lib/index.handler is undefined or not exported","    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)","    at Object.<anonymous> (/var/runtime/index.js:45:30)","    at Module._compile (internal/modules/cjs/loader.js:778:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)","    at Module.load (internal/modules/cjs/loader.js:653:32)","    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)","    at Function.Module._load (internal/modules/cjs/loader.js:585:3)","    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)","    at startup (internal/bootstrap/node.js:283:19)","    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)"]}
END RequestId: 29afd153-8a0c-4c60-b08f-db2883d4665d
REPORT RequestId: 29afd153-8a0c-4c60-b08f-db2883d4665d	Duration: 463.22 ms	Billed Duration: 500 ms	Memory Size: 512 MB	Max Memory Used: 24 MB	
Unknown application error occurred
Runtime.HandlerNotFound

**Comment by Hollerberg** [comment]
I see, you have to set `DT_LAMBDA_HANDLER` to the original value of your Lambda handler definition which is `LMBJVVMTOCOTIZACION/src/controllers/ProductController.selectProduct`.

```
DT_LAMBDA_HANDLER=LMBJVVMTOCOTIZACION/src/controllers/ProductController.selectProduct
```

The documentation `lib/index.handler` refers to the example used in the help page. Please let me know, how documentation can be improve to avoid misinterpretation.

The technical background is simple. Instead of your Lambda handler function, the AWS runtime will load and execute the OneAgent supplied handler function (`node_modules/@dynatrace/oneagent/index.handler`). OneAgent handler function reads `DT_LAMBDA_HANDLER` value to load and instrument your Lambda function.

**Comment by rolands7** [comment]
thanks for your help, we can already monitor the lambda, I have another query, the dynatrace module has a size of 14Mb and this causes the function to be edited by the web console, 

**_"The deployment package of your Lambda function "UE1COMDESALMBJOVVCORE001" is too large to enable inline code editing. However, you can still invoke your function."_**

Is it possible to put the node_modules in a lambda layer to have it separated, for the lambda function can it be editable from the AWS console?

**Comment by Hollerberg** [comment]
Currently moving OneAgent to a layer is not supported.
As this issue is out of serverless-oneagent plugin scope, may I ask you to open a Dynatrace support ticket if you want to follow up on that issue.
