### ISSUE TITLE
when will this project support node 12+?  

### ISSUE THREAD

**Issue by jordan112** [Dynatrace/serverless-oneagent#27]
We currently have to hold other dependencies (such as a serverless warmup plugin) at a lower version since this project doesn't appear to support anything above node 10.  thanks!

**Comment by Hollerberg** [comment]
Did you encounter an issue deploying a Node.js 12.x function with the plugin. There is no direct dependency of the plugin to the runtime version. Thus, it Node.js 12.x should work.

Please mind this [announcement](https://www.dynatrace.com/news/blog/dynatrace-launches-automatic-end-to-end-observability-via-traces-for-aws-lambda-preview-program/) - with the new preview program, OneAgent is deployed with a Lambda layer.
