### ISSUE TITLE
"custom" gets overwritten if it points to an external source (e.g. file)

### ISSUE THREAD

**Issue by mcsmcs** [Dynatrace/serverless-oneagent#3]
**Bug**
In the serverless.yml we specify the following for our `custom` attribute:

`custom: ${file(environment/${self:provider.stage}.js)}`

This lets us grab configurations based on the stage we want to operate on.  

When adding the the plugin, it determines that we are using the webpack plugin and then calls `preProcessServerlessWebPackDeployment` which in turn will set `service.custom.webpack.includeModules.forceInclude` on this.serverless wiping out the file path above.

This results in the configuration not being processed, and several errors:

```
Serverless Warning --------------------------------------
A valid service attribute to satisfy the declaration 'self:custom.environment.region' could not be found.
```

**Expected Behavior**
Allow the custom attribute to resolve before trying to append data allowing the configuration to interpolate correctly.

If it's not possible to do this programatically adding the configuration that this method is adding is minimal work and can be left to the consumer.

**Comment by Hollerberg** [comment]
Thanks for the report - I see the issue and will tie the pre-processing to an event. At event execution time variables are expanded and the plug-in is good to go to modify configuration.

**Comment by Hollerberg** [comment]
I just pushed npm package version 1.0.5 which should hopefully resolve the issue.
