### ISSUE TITLE
serverless monitoring  

### ISSUE THREAD

**Issue by rushins** [Dynatrace/serverless-oneagent#5]
hi 

i have servelress framework called openfaas and with lot of functions and i started installing the Dyantrace as we use dynatrace for all monitoring. .
 i am getting errors installing on our serveless. do you have any proper documentation steps for installing the agent . My current setup is kubernetes and serverlss runs on top of it as containers ?

**Comment by Hollerberg** [comment]
Hi, 
thanks for your inquiry. May I refer you to https://www.dynatrace.com/support/help/cloud-platforms/kubernetes. If this does not contain the requested information, please re-post your question at https://answers.dynatrace.com.
