### ISSUE TITLE
"@dynatrace/oneagent" may not be added to forcedIncludes

### ISSUE THREAD

**Issue by mfulton26** [Dynatrace/serverless-oneagent#8]
https://github.com/Dynatrace/serverless-oneagent/blob/aabfeb821193a9ee2126778be0a927a8893ebe91/src/index.ts#L393-L398

I believe this logic has a bug in it that if `"@dynatrace/oneagent"` is not already in the list it is not added but should be.

Suggestion:

```typescript
 if (forcedIncludes.includes(this.qualifiedNpmModuleName)) { 
 	this.logVerbose(`adding ${this.qualifiedNpmModuleName} already in ${forcedIncludes}`); 
 } else { 
 	this.logVerbose(`adding ${this.qualifiedNpmModuleName} to ${forcedIncludes}`); 
 	forcedIncludes.push(this.qualifiedNpmModuleName); 
 } 
```

if `Array.prototype.includes` cannot be used (pre node 6?) then `Array.prototype.some` can still be used but the log needs to be slightly different; e.g.:

```typescript
 if (forcedIncludes.some((mn) => mn === this.qualifiedNpmModuleName)) { 
 	this.logVerbose(`adding ${this.qualifiedNpmModuleName} already in ${forcedIncludes}`); 
 } else { 
 	this.logVerbose(`adding ${this.qualifiedNpmModuleName} to ${forcedIncludes}`); 
 	forcedIncludes.push(this.qualifiedNpmModuleName); 
 } 
```

**Comment by Hollerberg** [comment]
many thanks for bringing this up! I will correct and publish a new version.
resolved with 1.0.9
