### ISSUE TITLE
Release 1.0.10 is not published to npm yet

### ISSUE THREAD

**Issue by KingAlan198** [Dynatrace/serverless-oneagent#9]
Can 1.0.10 be published?  I need the node 10 support.

**Comment by Hollerberg** [comment]
Dear @KingAlan198 , 
thanks for your inquiry. AWS Lambda Node.js Version 10.x support has been added with OneAgent version 1.173.

**Comment by KingAlan198** [comment]
Sorry,  I corrected the release number I'm asking for.  Release 1.0.10 of this plugin changes a regular expression to work with "nodejs10.x" in the serverless.yml.  However this release is not available on npm, the lastest release of the plugin available on npm is 1.0.9.  I would like to be able to pull in serverless-oneagent 1.0.10 from npm.

[https://github.com/Dynatrace/serverless-oneagent/commit/f452dc2912a0c32dca234c8dccccec45d1449cd7](url)

**Comment by MichaelBosch** [comment]
Having the same issue.  Can this be published to NPM?

**Comment by Hollerberg** [comment]
sorry for the delay - I just published 1.0.10
